### ISSUE TITLE
Storing money in mongo and querying for it

### ISSUE THREAD

**Issue by funkybunky** [andylash/meteor-money#1]
Thank you for this package! :+1: 
How would you recommend storing prices and currency in the mongo collections?
I tried storing them as Money objects, but now face difficulties when I want to query for specific price values with the Collection.find() method, because I don't see a way how to query for the getter function getAmount(). If I access the value directly I have to deal with the multiplyer, which I wanted to avoid, because it's an implementation detail of your lib. Or do you think I need a wrapper, anyway? 
I hope my problem is understandable :)

**Comment by andylash** [comment]
Sorry this reply too so long.  I do store money objects in collections all the time.  But I assign a transform to all my collections, so that when they come out of the find they are typed objects and then the getAmount() method will work.  Did that make sense?

**Comment by funkybunky** [comment]
Hi, thanks for answering.
I ended up storing prices as integers manually using a constant multiplier (as it is recommended in the official Mongo docs) and convert it back only to show it in the UI. That way I can query for price using Collection.find( { price: XXXX } ) easily to get all items with the price XX.XX
I actually don't quite get what you mean. How do you use .find() to query for prices when they are stored as money objects? As far as I understand the docs (I may be wrong), the transform function just modifies what is returned by .find() ("Documents will be passed through this function before being returned from fetch or findOne"), so I guess this approach doesn't help for querying, right?

**Comment by andylash** [comment]
OK, now I understand.  Yeah if you want to do database queries (or even Meteor collection queries) you do need to query against how it's stored.  But you can still use the money object and just query against the amount field.  

Assuming you've got a Meteor Collection that stored Money objects called Moneys:

``` javascript
//return all Money objects that have a price of $US 10.25
Moneys.find( { 'amount': 1025, currency: 'USD'})
//If you aren't worried about different currencies, you could even do:
Moneys.find( { 'amount': 1025})
```

The downside here is you're basically encoding how many significant digits are stored for USD (this is different for other currencies like JPY).  I suppose you could do something like this to avoid retaining that knowledge in your calling code:

``` javascript
//return all Money objects that have a price of $US 10.25
Moneys.find( { 'amount': new Money(10.25, 'USD').amount), currency: 'USD' })
```

**Comment by funkybunky** [comment]
Thanks for the detailed answer!
Yes, that looks like a good approach, especially that last line where you avoid the hardcoding of the multiplier (significant digits). 
I guess I won't change my implementation now again, but if I need money support in future projects, I will consider this approach. And perhaps others who had the same problem can be inspired, too.
Thanks again for the package :)
